const characters = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9","~","`","!","@","#","$","%","^","&","*","(",")","_","-","+","=","{","[","}","]",",","|",":",";","<",">",".","?",
"/"];

let pw1 = document.getElementById("pass-1")
let pw2 = document.getElementById("pass-2")
const pwbtn = document.getElementById("pass-btn")
let passwordLength = 15

// function to get random character
function getRandomchar() {
    let randomIndex = Math.floor(Math.random() * characters.length)
    return characters[randomIndex]
}
// function to generate random character for range of desired length (passwordLength)
function generatePassword() {
    let randomPassword = ""
    for (i = 0; i < passwordLength; i++){
        randomPassword += getRandomchar()
    } 
    return randomPassword

}

//display generated password
function render() {
let randomPasswordOne = generatePassword()
let randomPasswordTwo = generatePassword()
    pw1.textContent = randomPasswordOne
    pw2.textContent = randomPasswordTwo
}

// pwbtn.addEventListener("click", generatePassword())
// let randomPasswordOne = generatePassword()
// let randomPasswordTwo = generatePassword()

// pw1.textContent = randomPasswordOne

// let randomPasswordOne = generatePassword()
// let randomPasswordTwo = generatePassword()
// console.log(randomPasswordOne)
// console.log(randomPasswordTwo)

    
// create 2 new variables generated by generatePassword() function
// 

    // pw1.textContent = randomPasswordOne
    // pw2.textContent = randomPasswordTwo


// document.getElementById("pass-btn").addEventListener("click", generatePassword())
// pw1.textContent = randomPasswordOne
// pw1.textContent = randomPasswordOne
// pw2.textContent = randomPasswordTwo